platform :ios, '11.0'

def shared_pods
  use_frameworks!
  
  pod 'SwiftLint'
  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'Kingfisher', '~> 5.4.0'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'R.swift', '~> 5.0.3'
  pod 'IQKeyboardManagerSwift', '~> 6.2.1'
  
end

target 'pizza-delivery' do
  shared_pods
end

target 'pizza-delivery-fake' do
  shared_pods
  # There is a bug with routing in v.1.4.6 so specific commit (which is newer) is used directly.
  #pod 'Swifter', '~> 1.4.6'
  pod 'Swifter', :git => 'https://github.com/httpswift/swifter.git', :commit => '56c89eaac4473d64ebea9e13a8fbc186f75bbb53'
end
