platform :ios, '11.0'

target 'pizza-delivery' do

  use_frameworks!

  # Pods for pizza-delivery
  pod 'SwiftLint'
  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'Kingfisher', '~> 5.4.0'
  pod 'MBProgressHUD', '~> 1.1.0'
  
end
